### ISSUE TITLE
JupyterCon Video 

### ISSUE THREAD

**Issue by lheagy** [pangeo-data/jupyter-earth#10]
As a part of the JupyterCon poster presentation (Poster being tracked in #9), we need to prepare a 2 minute video. 

From our meeting on [Aug 31, 2020](https://docs.google.com/document/d/1Od-7_FK1M9kLUkTiSMvAl2tmMwRJEdh-EySCMx5kndg/edit#heading=h.94y4wum37omj), here are some of the brainstorming ideas (my paraphrasing, so please correct me if I haven't captured your idea!):

- from @consideRatio:
    - We want something that hooks, catches attention
    - One way to do this is to identify and speak to recognizable pain points and then discuss: how we are making progress on this, how we solved it, or a call for community input depending on the results

- from @kmpaul: 
   - 2min is very short. We basically have time for either a quick overview on what it is we are doing or spend time telling people where to go to find more 
   - what do we have in terms of images that might capture the goals / structure / etc of the project? 

- from @LaurelOak: 
    - another option is to take the audience through a particular scenario -- demonstrating the interactive interface. Show the community a demo in a short min or two, potentially along the lines of the widget demos we have done in the past? 

Please add your ideas here! And we can then work towards developing a script.

**Comment by lheagy** [comment]
One presentation we could use as a bit of a starting point is the [overview one from the EarthCube meeting](https://docs.google.com/presentation/d/1oR-LmqSkUsFUZBWH4qz1TDnRzd2oWHxUXgYxqjUb3LY/edit)

**Comment by lrennels** [comment]
@lheagy if we go the rout of overviewing instead of addressing a particular pain point or scenario, it seems we could look to the poster, particularly the sections on (1) Project Goal (2) Jupyter + cloud: a scientific water hole and then close with (3) Connecting? The pizza box image as you suggest seems like a good one.

Happy to connect with you about working on this!

**Comment by lrennels** [comment]
I think that lots of our examples are digestible by humans, but I do remember that at @fperez 's talk at ERG the visual he did with CMIP5 data (as an example of CMIP6 data exploration needs) really caught people's attention... if only because the word **petabyte** is impressive.

**Comment by lheagy** [comment]
:+1: Thanks @lrennels! I quite like that combination -- it hints at the tech challenges, but primarily highlights the communities and broad role that Jupyter can play in being a connection point. What do you think is the best way to start stitching this together? another slide deck?

**Comment by lrennels** [comment]
I feel like a slide deck would be a good way to do it? I can look at what other people have done for these types of videos, I haven't seen the short ones for conferences before.  We could do a slide deck and then voice over it, use some of those graphics transitions we're told not to use but would probably be good for a video!

**Comment by lheagy** [comment]
Suggestion from @consideRatio, @fperez at the meeting today: focus on the watering hole analogy
- start with the project goal 
- large scale analysis + Pangeo with an example: e.g. interactive zooming from Scott Henderson and/or from @andersy005's demo  
- watering hole anology: science, community, outcomes 

Mechanics? 
- slides
- also have an embedded video ideally (maybe zoom or monosnap)

**Comment by lheagy** [comment]
Here is a slide-deck we can use to prep the video following the template outlined above: https://docs.google.com/presentation/d/1cwIu2upMH8VXotv5x7xpoxCGIrBjoo7cxWrZoXrhaGc/edit#slide=id.g989a77db85_0_55

**Comment by lrennels** [comment]
I have to make a video for a fellowship I'm applying for now as well, so I've been thinking about videos.  In terms of the actual production, we could use something like iMovie to put together stills and transitions and a VoiceOver.  I've done that before and it was fairly easy with good quality, but open to other ideas.

**Comment by lheagy** [comment]
:+1: That would great @lrennels! If we aim to record on Friday with @fperez, is that too tight on timing? (We are supposed to have the video + poster uploaded by the end of the day (anywhere on Earth) on Friday

**Comment by lheagy** [comment]
submitted! Thanks all 🚀
