### ISSUE TITLE
Show hidden files

### ISSUE THREAD

**Issue by consideRatio** [pangeo-data/jupyter-earth#107]
Let's enable the ability to show hidden files with the latest version of JupyterLab.

![image](https://user-images.githubusercontent.com/3837114/152840444-3419a4ed-e94f-46fd-85be-b4ca1c18b4a3.png)

https://github.com/berkeley-dsep-infra/datahub/pull/3210/files

### Related

The configuration seen in the image is an addition to a configuration defined elsewhere. See both:
- https://github.com/berkeley-dsep-infra/datahub/blob/a50e5936613f741b6beb9d0ac7cfa7b3f50f8ed3/hub/values.yaml#L69
- https://github.com/berkeley-dsep-infra/datahub/blob/50399c1561f9faa1d3214e8dbc310c2812bc644a/deployments/stat159/config/common.yaml#L51-L56

**Comment by fperez** [comment]
Yes, please! @consideRatio - any chance you could push this up to our hub as well? I think we're going to need it more and more... :)

**Comment by consideRatio** [comment]
THanks for the ping @fperez! It is now enabled!

**Comment by fperez** [comment]
Awesome, thanks a lot! Just checked and it works perfectly.
