### ISSUE TITLE
code-server (VSCode) not working correctly

### ISSUE THREAD

**Issue by JordiBolibar** [pangeo-data/jupyter-earth#137]
Since the last days I have started encountering different issues with code-server (VSCode in the browser). The colour themes no longer apply in the IDE and running code directly on VSCode is no longer possible. I seem to remember that this might have happened soon after a code-server update.

**Comment by consideRatio** [comment]
I've seen how the coloring in my terminal has changed as part of upgrading to ubuntu 22.04, which has also happened in the base image.

When you describe "running code on vscode is no longer possible", I don't yet understand what you mean. You could mean that you open a terminal and write `python mycodefile.py`, or press a button from a python code file to run the code, or that you browse a jupyter notebook etc and try to run code.

@JordiBolibar maybe you could provide a screenshot or gif animation? Preferably, an error message or a clear indication of the failure is included in it.

**Comment by JordiBolibar** [comment]
This is strange. The colour theme of VSCode is something that can be configured. Even when apply new ones now I cannot see any difference. The colour scheme changes on the bars and menus, but not on the IDE text, which seems to be overwritten somehow.

Regarding the running of code, the terminal seems to be dead (see image). Also, keyboard shortcuts or the "play" button don't work in order to run the code.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/2025815/179519307-361b0fda-c04b-4650-83c3-6acf8f91f222.png">

**Comment by consideRatio** [comment]
Thanks @JordiBolibar that was very helpful! I've opened #138 to address the coloring at least. I could reproduce the failure to open a functional bash terminal as well, and hopefully that is resolved by downgrading to code-server 4.4.0 as well.

I'm unsure how to get further logs from code-server erroring when opening a terminal, but i could get a definitive error message when using `ctrl+shift+p` and running the `Create terminal` command entry.

![image](https://user-images.githubusercontent.com/3837114/179524001-09c949bb-b800-4643-a049-24cdc98263eb.png)

**Comment by JordiBolibar** [comment]
I confirm everything is working well now. Thanks so much @consideRatio! 😄
