### ISSUE TITLE
code-server going out of sync

### ISSUE THREAD

**Issue by JordiBolibar** [pangeo-data/jupyter-earth#161]
Since today, I've started experimenting a really strange bug using code-server. After some minutes using it, whenever I save a file, it silently goes out of sync and it no longer updates the file I'm editing in Julia. In order to fix this, I have to copy paste the whole file, close the tab with code-server, launch it again, and paste the previous code. Whenever I do this, the new tab with code-server doesn't have the latest changes.

This is a really dangerous bug, it's driven me quite crazy all day. Luckily I've been mostly editing a single file, but if it impacts multiple files this becomes extremely time consuming and there's a lot of potential of missing changes.

Any idea where this could come from?

Thanks a lot in advance!

**Comment by yuvipanda** [comment]
Hi @JordiBolibar! I'm slowly taking over support of JMTE from the wonderul @consideRatio so it might take me some time to get myself familiarized enough to get to it.

Do you know what version of code-server is being run? I see in https://github.com/coder/code-server 4.9.1 is released, maybe we should try to update to that?

**Comment by consideRatio** [comment]
:heart: @yuvipanda!

I see that 4.9.0 is used:

https://github.com/pangeo-data/jupyter-earth/blob/09fe9f2c79ed0a213216f7dd8568c62d44dc16d9/hub.jupytearth.org-image/Dockerfile#L77-L82

The image was built most recently Dec 13, 2022, and the associated commit is used by the configurator at https://hub.jupytearth.org/services/configurator/.

The process to update the image is 1 build automatically by merging pr here etc, 2 updating the configurator to use the most recent commit.

I used `latest` a while, but there was a failure associated with doing so where a long running user server got dask workers with "the same image" which pulled in a newer latest, and had issues.

**Comment by JordiBolibar** [comment]
Thanks a lot @yuvipanda and @consideRatio! Some additional context: I realized that sometimes it takes a while for code-server to save the file. Now sometimes I have to wait like 30s up to 1min to get it saved. Maybe what I was experiencing before was an extreme case of this?

**Comment by JordiBolibar** [comment]
Hi @yuvipanda. For now the problem seems to have disappeared, so I think I can close this for the time being. If it goes back I can always comment here again. Thanks for the help! :)
