### ISSUE TITLE
Book build failing 

### ISSUE THREAD

**Issue by lheagy** [pangeo-data/jupyter-earth#20]
It looks like our JupyterBook is failing on an error with `nbconvert`. https://github.com/pangeo-data/jupyter-earth/runs/1368344069. @choldgraf: is this one you are familiar with?

**Comment by choldgraf** [comment]
Have a Léonie on top of me now so can't get to computer but my guess is that it has to do with the relative ordering of the dependencies in requirements. txt

**Comment by consideRatio** [comment]
> myst-nb 0.10.1 requires nbconvert~=5.6, but you'll have nbconvert 6.0.7 which is incompatible.

I think then the solution is to make the myst-nb dependency go higher up, because only the first to declare the dependency seem to get its version constraints met.
