### ISSUE TITLE
Widgets are missing when viewing the Mouna Loa example in Binder

### ISSUE THREAD

**Issue by whyjz** [pangeo-data/jupyter-earth#39]
Hi -- I am trying to view this Jupyter Widgets tutorial using Binder:
https://pangeo-data.github.io/jupyter-earth/jupyter-resources/widgets.html

And I realized that Jupyter Lab interface can show the plot, but all the widgets -- slidebars, checkboxes, menus -- are missing, as this screenshot shows:
![scr_003](https://user-images.githubusercontent.com/19339926/105564686-4639d100-5cf1-11eb-8060-ba555ae49157.png)

And ideas for addressing this issue are much appreciated -- Thanks in advance!

**Comment by lheagy** [comment]
We should be back in action now!

![image](https://user-images.githubusercontent.com/6361812/108564147-e28acf80-72bf-11eb-9002-884082ab352d.png)
