### ISSUE TITLE
Explaining the concept of "ecosystem"

### ISSUE THREAD

**Issue by whyjz** [pangeo-data/jupyter-earth#42]
Hello folks -- I mentioned this at today's meeting, and here I'd like to elaborate it maybe a bit more and see what you think:

The word "ecosystem" is ambiguous when used as things like Jupyter ecosystem. I still remember I checked up some dictionaries and webpages for what it exactly means but with no luck, and that was not even a long time ago. I feel that there might be many geoscience people who aren't used to this concept, and maybe it's good to spend a paragraph or two explaining the idea behind this ecosystem jargon on the introduction page?

Many scientists working in the geoscience domain may know what a toolbox (as of Matlab) or a plugin (as in GIS) is. Thus they might be confused with the dependency level when referring to different Jupyter-related tools/packages as part of the Jupyter ecosystem. Not to mention that there is a "Jupyter ecosystem" vs. a "Pangeo ecosystem," as shown in the current tutorial. 

My current understanding of an ecosystem (please correct me if I am wrong) refers to a collection of independent packages. Each has a specific purpose, such as parsing data, providing UI, parallel computing, or visualizing results. Those packages need to work together in order to complete a workflow of data analysis. I'd be happy to provide anything to the current tutorial if you think this is useful.

**Comment by lrennels** [comment]
As someone still fairly new to the "ecosystem" beyond notebooks I'd also happily be a guinea pig here!

**Comment by whyjz** [comment]
Closing this issue as we've created some content for this. The follow-up discussion can be together with #33.
