### ISSUE TITLE
Z2JH user-scheduler in need of maintenance

### ISSUE THREAD

**Issue by consideRatio** [pangeo-data/jupyter-earth#5]
The user-scheduler is a tool that help our Z2JH deployments scale down by allocating new arriving users to the nodes where most users already resides. It is now in need of maintenance, and I describe this further in Z2JH: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1730

Here is [a comment by Min](https://github.com/pangeo-data/helm-chart/issues/58#issuecomment-419372599) about the user-scheduler.
>I can't overstate how cool the new scheduler is. Our first 24 hours with it and it successfully scaled down from 5 to 2 nodes. We shipped 0.7 last week, and I'm already more excited about getting our 0.8 release ready!
>
>The manual solution that's been the only feasible scale-down is to cordon nodes that you don't need anymore and wait for them to drain and be reclaimed by the cluster autoscaler. They may still need manual draining to get pods other than users off of them that prevent scale-down (e.g. a miscellaneous kube-dns pod can show up).

**Comment by choldgraf** [comment]
I'm a big +1 on this, as I think it's important for any institution that cares about efficiency in resource usage (and TBH this is also something that will be important for 2i2c!)

**Comment by consideRatio** [comment]
Working on this became a high priority as [a PR](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1699/files) made [things crash](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1773) on k8s version 1.15 and older.

The work I put in relates to the [z2jh issue about maintaining it](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1730), [the issue about the error](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1773), [a PR where I resolve the issues and maintains the user-scheduler logic](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1778), and [a complementary PR fixing details](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1782) I got wrong on the first attempt.
