### ISSUE TITLE
Manually added users to hub.jupytearth.org

### ISSUE THREAD

**Issue by consideRatio** [pangeo-data/jupyter-earth#53]
For convenience in the short term while the automation and such to manage users via GitHub is setup, I suggest students and instructors are added via https://hub.jupytearth.org/hub/admin but also that any such manual addition of users is documented here.

When documenting it here, clarify username, full name, and if the user is a student, instructor, or something else. I'm providing the template below that can be copy-pasted into a comment.

```
I've added users manually at https://hub.jupytearth.org/hub/admin and here maintain a list of those that I've added in this comment that I'll update over time.

GitHub username | Full name | Role
-|-|-
username1 | Alice Bobsson | Instructor
```

**Comment by abbyazari** [comment]
I've added users manually at https://hub.jupytearth.org/hub/admin and here maintain a list of those that I've added in this comment that I'll update over time.

GitHub username | Full name | Role
-|-|-
lcgasque | Claire Gasque | Instructor

**Comment by fperez** [comment]
Excellent, thanks @abbyazari and @consideRatio!

**Comment by consideRatio** [comment]
I've added users manually at https://hub.jupytearth.org/hub/admin and here maintain a list of those that I've added in this comment that I'll update over time.

GitHub username | Full name | Role | Comment
-|-|-
ian-r-rose | Ian Rose | dask-labextension developer | Added for helping out in https://github.com/dask/dask-labextension/issues/203#issuecomment-888177777.

**Comment by whyjz** [comment]
As this thread seems inactive, what do you think if we move the documentation elsewhere, remove the personal information, and close this issue @consideRatio ?

**Comment by abbyazari** [comment]
Yes it's inactive. We can remove user names and details or move privately. Fine on my end.

**Comment by consideRatio** [comment]
We haven't kept track of our user list overall, but i think it was great that you kept track of the larger group of temporary accounts to be added/removed @abbyazari! Thank you!

If we are to add a group of temporary accounts again, I suggest we do the same.
