### ISSUE TITLE
jupyter/docker-stacks maintenance

### ISSUE THREAD

**Issue by consideRatio** [pangeo-data/jupyter-earth#6]
jupyter/docker-stacks images are widely used still but lacks mainteners. I'd like to do some maintenance work there generally but also specifically I'd like finish work on a bigger PR to make the startup scripts more robust: https://github.com/jupyter/docker-stacks/pull/1052

**Comment by choldgraf** [comment]
Hmm - +1 on anything that will reduce maintainer burden in the future :-)  do you imagine using docker-stacks in Pangeo?

**Comment by consideRatio** [comment]
I went ahead and closed the PR i referenced in docker-stacks (1052), it grew too large and I felt it was unrealistic to get it merged. It is very complicated trying to make a bigger change both incrementally and all in one go.

I'll go ahead and close this issue as well.

**Comment by consideRatio** [comment]
I didn't have a good idea on what Pangeo would do for their images, but at this point they are unrelated to jupyter/docker-stacks based images. Development is here: https://github.com/pangeo-data/pangeo-docker-images.
