### ISSUE TITLE
Jupyter Book video / slides

### ISSUE THREAD

**Issue by choldgraf** [pangeo-data/jupyter-earth#61]
Hey all - I made a short "intro to Jupyter Book" video. It is about 23 minutes long. It covers the basic things that happen in a build, discusses a bit of MyST, and talks about some features that folks might find interesting. It is intentionally light on depth and details :-)

Here are the slides:

https://docs.google.com/presentation/d/1mZJo5H-FyncaAV5W7zBm6jNBaJPaXFCGtlQoJXwTrX4/edit?usp=sharing

And here is the video:

https://drive.google.com/file/d/17djlvZKP0lxu_BNf9j8DskBiLx8MBUV5/view?usp=sharing

**Comment by whyjz** [comment]
Closed with #108.
