### ISSUE TITLE
JMTE annual report draft and action items 

### ISSUE THREAD

**Issue by whyjz** [pangeo-data/jupyter-earth#64]
Hi team - [here's the link](https://docs.google.com/document/d/1qhbiZuU0_FWOwVtjwcM5Ku4JsnYXATIhavLz5nTKxRc/edit?usp=sharing) to the draft of our annual report. @lheagy and I have made a very rough version, and it would be great if you can directly edit it or let me know your thoughts/progress/comments. Also please let me know if you can't access it. 

I have made a milestone and tagged the issues I think worth mentioning or dealing with before the report dues. Some of them are closed, but the others are still active. Please feel free to apply or remove this milestone tag to any issue as you see fit!  

#61 Jupyter Book video / slides (onboarding resources)
#51 and #59 [**closed**] 2021 EarthCube meeting materials
#50 progress on JupyterLab RTC (JupyerHub improvements)
#38 Project Pythia (onboarding resources)
#33 Creating onboarding and learning resources on jupytearth.org (onboarding resources)
#18 Development task: Tools for managing complex JupyterHub deployments (JupyerHub improvements)
#15 Scientific discovery through interactive computing: Widgets and dashboards (new tools for earth science) 
#14 Data discovery: JupyterLab extensions for data catalogs (new tools for earth science) 
#11 A curated list of learning resources (onboarding resources)
#9 and #10 [**closed**] 2020 JupyterCon materials
#3 Automatic HTTPS setup for BinderHub (JupyerHub improvements)
Also, we have 2020 AGU meeting materials from Google drive!

**Comment by lheagy** [comment]
Hi @whyjz, this is looking great! I added a few comments in the google doc. Please let me know if there is anything that isn't clear or would be helpful to chat about
