### ISSUE TITLE
JupyterHub official Grafana metrics dashboard

### ISSUE THREAD

**Issue by consideRatio** [pangeo-data/jupyter-earth#7]
JupyterHub expose a lot of metrics, such as how many currently running users it has. With a tool like Prometheus, these metrics can be collected over time into a timeseries. With a tool like Grafana, these collected metrics can be presented in a Dashboard.

But these dashboards needs to be defined and configured. Grafana has a format for this, and when its done they can be exported to .json files that others can import.

As an example, here are two graphs from a dashboard that I got by asking @yuvipanda who linked a 2i2c deployment for University of Toronto. I exported it from the grafana instance using their web ui as a .json file, and imported it into my grafana instance.

![image](https://user-images.githubusercontent.com/3837114/88667374-92f57400-d0e1-11ea-91d6-47686e19d172.png)

My vision is that there is a JupyterHub official dashboards, and perhaps a Z2JH official dashboard to use.

**Comment by choldgraf** [comment]
This is a cool idea - I suppose if something like this would have existed it could have helped you out getting started w/ a grafana board for the hackademy, yeah?

I guess my main question is how general we could make this so that it doesn't bit-rot and that it remains useful to people without a lot of upkeep. Does that seem attainable?

**Comment by yuvipanda** [comment]
We can publish dashboards here: https://grafana.com/grafana/dashboards.

@choldgraf The way to do it probably is to have a git repo somewhere that folks can make PRs to, and then we can publish to grafana.com (or just keep the repo). This way, as you make improvements locally you can publish them - and then pull them in so you are level with upstream...

**Comment by AndreaGiardini** [comment]
I am interested in this. Any pre-existing dashboard that would make sense to publish already?

**Comment by consideRatio** [comment]
@yuvipanda wrote:
> The way to do it probably is to have a git repo somewhere that folks can make PRs to, and then we can publish to grafana.com (or just keep the repo).

Hmmm, what about:

- A repo with CI to automate publishing to Grafanas dashboards to keep it updated there.
- Exploration and docs to make use of the dashboards in a way that reduce manual work to setup to the lowest needed level.

@AndreaGiardini the dashboard in github.com/neurohackademy/nh2020-jupyterhub is the latest version ive used with z2jh

**Comment by yuvipanda** [comment]
Pathways to doing this 'right':

- https://www.weave.works/blog/grafana-dashboards-as-code/
- https://github.com/weaveworks/grafanalib
- https://github.com/grafana/grafonnet-lib

**Comment by yuvipanda** [comment]
After getting tired of copy-pasting, I built this today: https://github.com/yuvipanda/jupyterhub-grafana. It's pretty complete! It needs documentation and some code cleanup - particularly around splitting the JSONNet files. But it works great, and I like it :)

**Comment by yuvipanda** [comment]
@consideRatio you should be able to check it out at http://grafana.utoronto.2i2c.cloud/d/i8G_l9bMk/jupyterhub-dashboard?orgId=1.

**Comment by consideRatio** [comment]
@yuvipanda excellent work on this! :heart_eyes: I'm looking forward to trying it out properly but haven't yet

**Comment by Q-lds** [comment]
Am I wrong or at the moment all the dashboards presented above are not really compatible with the basic jupyterhub installation?

I was also looking at some of the screenshots provided by @yuvipanda repo, and almost all the metrics don't seem to be present on my hub /metrics page .  Or am I missing something entirely?

**Comment by adam0s9** [comment]
Hello everyone, 

Is there any update on this? 

Thank you,
Best Regards,
a.

**Comment by consideRatio** [comment]
https://grafana.jmte.2i2c.cloud/ is up and running, but individual users need to be granted access.

@adam0s9 note that I write nothing further as your account is anonymous and newly created, making me suspect you to be a bot etc.
