### ISSUE TITLE
Erik's AGU talk planning

### ISSUE THREAD

**Issue by consideRatio** [pangeo-data/jupyter-earth#71]
Notes sketched during meetings about planning an ACU talk / poster submission.

- [x] Gather info about the talks' format
  - Title
  - Abstract: Max 2000 characters
  - Virtual live presentation is 10 to 15 minute presentation
  - A full session takes an hour or two and involves ~6-8 talks and Q&A after each talk. If a session receives more than that, the other will be presented in a poster format.
  - The abstract submission will be used to decide if they can accept the submission as a presentation or as a poster.
  - Submission process: submit, get accepted for a certain format (talk, poster), then you have ~3 months to prepare the concrete content.
  - Deadline for submission: 4th August
- [x] Find reasonable session to submit to:
  - [List of sessions](https://agu.confex.com/agu/fm21/prelim.cgi/Home/0)
  - [IN004 - Adopting Principles to Enhance Capabilities for Using Earth Science Data](https://agu.confex.com/agu/fm21/prelim.cgi/Session/120797)
    > Other __principles, standards, and practices also contribute to improving capabilities for reusing data__. Session presentations describe how adoption of such capabilities enable, facilitate and/or enhance use of Earth science data.
  - [IN009 - A Moonshot Ambition: Creating a Globally Integrated infrastructure to Find, Access, Interoperate and Reuse Earth and Environmental Science Data to address Global Challenges.](https://agu.confex.com/agu/fm21/prelim.cgi/Session/121360)
    > This session solicits papers from researchers working at the programme, project, or group level that demonstrate results in achieving the ambition of a global Earth and environmental __research infrastructure commons__, maximising the potential to contribute to known (and unknown) global challenges.
  - [IN016 - Cloud Computing's Support for Earth and Space Informatics has Become a Sophisticated Solution to Computing Needs](https://agu.confex.com/agu/fm21/prelim.cgi/Session/123954)
    > This session seeks use cases and scenarios to __highlight the reasons for adoption and barriers to the adoption of scientific cloud computing__. Abstracts should describe use cases, benchmarks, and real-world examples of the scientific use of cloud computing.
  - [IN020 - Data and Information Services for Interdisciplinary Research and Applications in Earth Science](https://agu.confex.com/agu/fm21/prelim.cgi/Session/120406)
    > Presentations addressing the specific industry and __societal needs, best practices, learned lessons and new challenges in cloud computing__, big data, AI/ML (artificial intelligent/machine learning), data provenance, and scientific reproducibility, regarding information access, visualization, and analysis, are highly encouraged.
  - [IN030 - Open-Source Software, Notebooks and FAIR Software](https://agu.confex.com/agu/fm21/prelim.cgi/Session/122569)
    > This session will look at __the role of FOSS, cloud-based architecture solutions, metadata, online notebooks and other user interfaces to support information sharing, scientific collaboration, scientific reproducibility__, QA/QC and analytics at scale solutions.
  - [IN034 - Science In Application Containers](https://agu.confex.com/agu/fm21/prelim.cgi/Session/119658)
    > This session will encompass topics such as building and __running containers, open source packages and environment setups that can be used by the earth science community__, container usage in CI/CD, and availability of containers to be used for scientific experiments. We encourage submissions from anyone who is using containers to run scientific code.

- Scope a narrative for talk
  - [x] Brainstorm pieces
  - [x] Structure a narrative
  - [x] Flesh it out
  - [ ] Add speaker notes
  ![image](https://user-images.githubusercontent.com/3837114/126192133-447d48e5-976e-49c1-b98c-1842a600ca8b.png)

### Talk ideas

__Initial brainstorm on topics by Fernando__
- Deployment in the cloud, working concretely with domain scientists with needs that are flexible and evolving. How to make use of standard things and put it together into a tailored development for the needs of the users.
- What have I learned and what is possible?
- RTC, welcoming students, auth with github, SSH, magic_castle...

__Long time goal of a deployment for researchers, they can choose and combine__
- Hardware options
- Environment options: JupyterLab, VSCode, VNC, SSH

__What are possibilities now in JupyterHub deployments?__
- SSH to server
  - rsync
  - sftp
- VNC to server
- JupyterLab in server
- VS Code

__The evolving role of a cloud based JupyterHub__

- JupyterHub provides easy access to an Jupyter based environment.

- Evolution on several levels
  - _JupyterHub itself_ is evolving (RBAC)
  - _JupyterHub distributions_ are evolving (TLJH, Z2JH)
  - _JupyterHub aware services_ are evolving (jupyterhub-ssh, jupyterhub-sftp, jupyter-idle-culler, daskhub, binderhub)
  - _JupyterHub user environments_ are evolving (JupyterLab, VS CODE, RStudio, Remote desktops)
- Flexibility on several levels
  - _JupyterHub deployments_ can be tailored
  - _JupyterHub user environments_ can be tailored
  - _JupyterHub's cloud environment_ can be tailored

### Abstract proposal draft

https://hackmd.io/@29EjZnuAQx-ME7Olgi2JXw/ryTguWByK

### References
- [Abstract proposal draft](https://hackmd.io/@29EjZnuAQx-ME7Olgi2JXw/ryTguWByK) - Comments very welcome!
- [Submission portal](https://agu.confex.com/agu/fm21/prelim.cgi/Home/0)
- [(Private) My submission draft in AGU](https://agu.confex.com/agu/fm21/in/papers/index.cgi?username=835265)

**Comment by whyjz** [comment]
One quick thought about the session selection: [IN004 (Adopting Principles to Enhance Capabilities for Using Earth Science Data)](https://agu.confex.com/agu/fm21/prelim.cgi/Session/120797) might be the other possibility. [IN030](https://agu.confex.com/agu/fm21/prelim.cgi/Session/122569) emphasizes the support of collaboration (using JupyterHub), and IN004 focuses on the ways we use/share Earth Science data (again using JupyterHub). For me, both topics would be a good fit for the proposed abstract.

**Comment by whyjz** [comment]
Here are some questions we can attack in the abstract, which might interest earth science people:

- Why do we need JupyterHub? Isn't the traditional way (e.g. ssh login to a server) just fine?
- If my team is all using Matlab (which is true for a great portion of the ES community), How do we switch to JupyterHub collaboration, and what are the benefits for that?
- How steep is the learning curve of JupyterHub? Do we need a tech-savvy person for my team to manage the deployment?
- How does JupyterHub make the earth science data (or code) more [FAIR](http://www.copdess.org/enabling-fair-data-project/)?
- Do only the people who have to work with big data need JupyterHub? A more generic form of this question would be: who needs JupyterHub? Maybe geophysicists/oceanographers/atmosphere people for sure, but what about geochemists, structural geologists, and the people with expertise of [the other sub-domains](https://www.ccsu.edu/geolsci/careers.html)? This is heavily domain-specific so I think maybe we can revisit this several times as we flesh out the abstract and the presentation content.

**Comment by kmpaul** [comment]
To avoid confusion and aid in searchability, I think the typo in the issue title should be corrected to say "Erik's AGU talk planning".

**Comment by consideRatio** [comment]
@whyjz thank you so much for helping me scout for sessions of relevance, and onboarding me personally into this, and brainstorming of relevant content to talk about! I'm more thankful than you will know! Thank you!!

I'm feeling quite confident about the format at this point and think that I can start considering a more concrete topic fitting of a 10-15 minute talk / poster of relevance to the IN004 or IN030 sessions - this is my next step. I look to have something to outline by Monday, 2nd Aug.

**Comment by consideRatio** [comment]
@andersy005 i'm trying to reach you, are you able to check Pérez group slack?

**Comment by consideRatio** [comment]
Abstract submitted!!

**Comment by whyjz** [comment]
@consideRatio I am closing this issue as its major goal (abstract submission) is done. We can reopen this issue or set up a new one for the upcoming presentation if needed.
