### ISSUE TITLE
Update Cartopy to 0.20

### ISSUE THREAD

**Issue by fperez** [pangeo-data/jupyter-earth#84]
Unfortunately there's a bug in the version we have that's causing me some headaches - [details here](https://github.com/berkeley-dsep-infra/datahub/issues/2824). The real urgency for me is on the D100 side, which is why I filed it there, but it's also a problem here, might as well fix it in both places...

**Comment by consideRatio** [comment]
![image](https://user-images.githubusercontent.com/3837114/135634378-2ede2c0d-6b0b-445c-b0fd-8bbde5a55f54.png)

Cartopy has been updated in conda-forge to 0.20.0, 27 minutes ago!

**Comment by consideRatio** [comment]
Resolved!

![image](https://user-images.githubusercontent.com/3837114/135643941-70230dc0-de8e-4f10-ab8e-cfdb286eb144.png)

**Comment by fperez** [comment]
Wonderful, thank you so much!!!
