### ISSUE TITLE
JupyterCon Poster

### ISSUE THREAD

**Issue by lheagy** [pangeo-data/jupyter-earth#9]
For JupyterCon 2020, we need to put together a poster for our [accepted abstract](https://docs.google.com/document/d/1f0r0OuGk2W5nIzUHenqRuDUuCQ-NwYP4Wzh7nor4QkM/edit) and have it submitted by **Sept 11, 2020** along with a 2min video (being tracked in #10). The description of the poster session is available on the [JupyterCon website](https://jupytercon.com/talk-poster-cfp/
).

## Poster 

The draft of the poster is on a [google slide](https://docs.google.com/presentation/d/14WqZuCyco_wATFIf9AFvtPdnnEr1CbAwUkxmcGgEA_o/edit#slide=id.p). The tentative outline we have is:

- Team 
- Project Goal
- The Pangeo Project
- Research use-cases
- Jupyter developments (highlighting developments of interest both to Researchers as well as Jupyter developers & contributors)
- Connecting
- Acknowledgements

## Action items
- [x] description of the Pangeo project: what aspects would we like to highlight?
- [x] short description (2-3 sentences) + image for each of the research areas
    - [x] hydro (cc @ EMscience, @LaurelOak)
    - [x] cryo (cc @facusapienza21, @alicecima: do you have an image or figure in mind that we could use?)
    - [x] geophysics (cc @lheagy)
    - [x] climate (cc @jhamman, @andersy005)
- [x] highlights of developments in Jupyter + Pangeo (cc @consideRatio: would you be willing to lead this section?)
- [x] connecting: project website, Pangeo website + discourse, Jupyter website + discourse, anything else? 

Please feel free to directly edit the poster, or if you are working and need scratch-space, you are welcome to make a new slide and play with content there. 

## A few questions
- are we missing any big-picture items on the outline? 
- anything we should emphasize or de-emphasize? 
- are there other calls / opportunities for community involvement that we would like highlight?

**Comment by consideRatio** [comment]
Yepp I can take lead on the developments in Jupyter + Pangeo section @lheagy! My mental plan is to get started by drafting a text and then request for comments, from there we could better delegate. I think I'll let the recent annual project report act as a starting point of what to consider writing about initially.

**Comment by lheagy** [comment]
@fperez and I spent some time chatting about the poster today, and a couple items that we discussed highlighting specifically for this audience are: 
1. the role of Jupyter for science in the cloud - interdisciplinary scientific communities can grow in the cloud: e.g. a watering hole analogy. Jupyter in the cloud is a space with available data and where open infrastructure facilitates interaction 
2. the pattern of developing open standards, in a vendor-agnostic way, and upstreaming developments as appropriate 

To give space for this, we moved the panels around just a touch: so in the center, there is space for a brief overview of the research areas and main areas of Jupyter we are working in, and on the right, there is now space for discussion on some of the philosophy of the project. 

See what you think and feel free to add your thoughts!

**Comment by lheagy** [comment]
@consideRatio, just a couple thoughts on the wording for the Open Source section. I am thinking to try and highlight a few different areas of contribution: shared infrastructure, interactive computing, and communicating results. See what you think of my suggestion below and feel free to adapt as you see fit! 

Current version 
> We contribute across a *_wide tech stack_* already internationally adopted. Contributions range from making it easier for system admins to provide essential infrastructure on Clouds & HPCs to improving researchers potential to compute and collaborate within such infrastructure and finally communicate their findings.

Suggestion 
> We contribute across a *_wide tech stack_* that has been internationally adopted. Contributions range from making: making it easier for system admins to provide *_shared computational infrastructure_* on the Cloud and HPC centers, to enabling *_interactive computing_* with research code, to facilitating the *_communication_* of findings

**Comment by lheagy** [comment]
submitted! Thanks all 🚀
