### ISSUE TITLE
Colorizing things in our terminals

### ISSUE THREAD

**Issue by consideRatio** [pangeo-data/jupyter-earth#91]
@whyjz asked about `ls --color=auto` and such. I'm creating this issue to represent the wish to get things colorized in our terminals. I figure perhaps I should try upstream this directly to the pangeo base stacks to solve it for all of us in one go.

**Comment by fperez** [comment]
Doing that system-wide so it's a default for all users requires editing `/etc/profile`, as [explained here](https://unix.stackexchange.com/questions/48870/global-bash-profile). It would be fine to have a slightly nicer default, though users will find again the "bare" ones on any other non-customized image they encounter (most).

Instead, I think we should just explain to people (not here, but in the generic user-facing docs for jhub/2i2c hubs) how to configure their setup. The only point that really needs making is the above about the two files, that same issue happens in OSX and is [explained here](https://joshstaiger.org/archives/2005/07/bash_profile_vs.html). JLab in that regard is like OSX that all shells it opens are login shells. 

Let's close this issue for now, but mentioning the config explanation in any relevant user docs is probably a good idea.
