### ISSUE TITLE
Update Julia to v1.7.1 in JupyterHub

### ISSUE THREAD

**Issue by JordiBolibar** [pangeo-data/jupyter-earth#94]
Would it be possible to update the Julia version in the JupyterHub to the more recent [v1.7.1](https://julialang.org/downloads/)? It includes some nice additional features that I would like to use for my project. Thanks!

**Comment by consideRatio** [comment]
@JordiBolibar when https://github.com/pangeo-data/jupyter-earth/runs/4814421437?check_suite_focus=true reports to be complete, you can restart your user server and you will have Julia 1.7.1!

**Comment by JordiBolibar** [comment]
Awesome, thanks a lot @consideRatio!

**Comment by JordiBolibar** [comment]
Hi @consideRatio, would it be possible to delete the `.julia/lib` folder? New Julia versions often mess with some precompiled cached packages. Is there any way for me to do that or I'd need sudo access? Thanks again for your help!

**Comment by consideRatio** [comment]
Hi @JordiBolibar!

Is the `.julia/lib` located in your home folder? Then you have permission to just delete it straight up with `rm -rf ~/.julia/lib` from a terminal.

**Comment by JordiBolibar** [comment]
Strangely, I cannot find it in my home folder. I have also looked around for a while in other root folders and I couldn't find it. I thought it might be tied to the admin user who has sudo access. Anyway, I'll keep investigating...
