### ISSUE TITLE
Installing pyMC3

### ISSUE THREAD

**Issue by consideRatio** [pangeo-data/jupyter-earth#99]
In #98 i tried to install pyMC3 according to [these instructions](https://github.com/pymc-devs/pymc/wiki/Installation-Guide-(Linux)#pymc3-installation-for-linux) but [failed](https://github.com/pangeo-data/jupyter-earth/runs/4943506072?check_suite_focus=true) because...

```
Encountered problems while solving:
  - package mkl-service-2.3.0-py39h07f9747_1 requires mkl >=2020.2,<2021.0a0, but none of the providers can be installed

conda-forge/noarch        
conda-forge/linux-64      
The command '/bin/sh -c echo "Installing conda packages..."  && mamba install -n ${CONDA_ENV} -y         altair         bqplot         plotly         python-kaleido         seaborn         ipycanvas         ipympl         jupyter_bokeh         jupyterlab-geojson         black         flake8         pep8         pyflakes         pylint         pytest         pytest-cov         jupyter-book         jupytext         numpydoc         sphinx         pymc3         theano-pymc         mkl         mkl-service         ipydatagrid         ipyparallel         lxml         pyhdf         vaex         mhealpy         pytables         statsmodels         xlrd         jupyter-repo2docker         jupyter-vscode-proxy         "jupyterlab>=3.2.4"         "jupyterlab-link-share>=0.2.2"         jupyterlab-git         jupyterlab-system-monitor         nbdime         qgis         retrolab         ipydrawio         websockify         compilers         cxx-compiler         cython         fortran-magic         google-cloud-sdk         sympy         cupy         cudatoolkit=11.2.2  && echo "Installing conda packages complete!"' returned a non-zero code: 1
```

It isn't clear to me what's the core issue is yet, but I'll try to resolve it and follow up in this issue.

/cc: @abbyazari @facusapienza21 who are interested in this

**Comment by consideRatio** [comment]
# Investigation

**Comment by consideRatio** [comment]
Closing as resolved, `import pymc3` now works.

For reference, @fperez made a comment about removing the `nomkl` package (that is a dummy package to make sure `mkl` isn't installed) and installing `mkl` as a dependency: https://github.com/pangeo-data/jupyter-earth/pull/100#issuecomment-1021736812

**Comment by fperez** [comment]
BTW, it seems to me that this can now be closed, right? In light testing everything worked fine for me - @abbyazari/@facusapienza21, pls let us know if you encounter any issues...
